export const types = {
  uiOpenModal: "[ui] Open Modal",
  uiCloseModal: "[ui] Close Modal",
  eventSetActive: "[event] Add Set Active",
  eventLogout: "[event] Logout event",
  eventAddNew: "[event] Add new",
  eventStartAddNew: "[event] Start Add New",
  eventClearActiveEvent: "[event] Clear active event",
  eventUpdated: "[event] Event updated",
  eventDeleted: "[event] Event deleted",
  eventLoaded: "[event] Events loaded",
  authCheckingFinish: "[auth] Finish checking login state",
  authStartLogin: "[auth] Start login",
  authLogin: "[auth] Login",
  authStartRegister: "[auth] Start register",
  authStartTokenRenew: "[auth] Start token renew",
  authLogout: "[auth] Logout",
};
